// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using garderie.app2.Server.Data;

#nullable disable

namespace garderie.app2.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250818182403_AddKids")]
    partial class AddKids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("garderie.app2.Server.Models.Entities.Daycare", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Daycares");
                });

            modelBuilder.Entity("garderie.app2.Server.Models.Entities.Kid", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("daycareId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("daycareId");

                    b.ToTable("Kids");
                });

            modelBuilder.Entity("garderie.app2.Server.Models.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("garderie.app2.Server.Models.Entities.Daycare", b =>
                {
                    b.HasOne("garderie.app2.Server.Models.Entities.User", null)
                        .WithMany("Daycares")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("garderie.app2.Server.Models.Entities.Kid", b =>
                {
                    b.HasOne("garderie.app2.Server.Models.Entities.Daycare", "daycare")
                        .WithMany("Kids")
                        .HasForeignKey("daycareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("daycare");
                });

            modelBuilder.Entity("garderie.app2.Server.Models.Entities.Daycare", b =>
                {
                    b.Navigation("Kids");
                });

            modelBuilder.Entity("garderie.app2.Server.Models.Entities.User", b =>
                {
                    b.Navigation("Daycares");
                });
#pragma warning restore 612, 618
        }
    }
}
